sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: GUkd4vlZrPpLrOja2DlFWtRhQSUG2WpP7nFcT/C9NnVPplNm5NuqprH9yJerwJP1Hqn+w24hGYVybC886GjaqexE7Pp2PnjXipya19vY+f1LGxtlmOk93MxHXO7+bl5M4THTtm3XToNvoxyU1ZYljhLEDhGddKbpjODx6MB+rBXblJymv20rSbpXW2LsFtV6zkNQSS/gTBhQ5ZV049ypYK9m/yTCenDO51wkUGz63zyYmrsPQRZJPzzGl/MfLfYju2ylBzxrdLChjvLkyW1VC04cE1Qd+YeC49eP4oLb2F7f2IrJNlk5ZK3nI73N4gzGL+J7D4gcyPtxiinQOlxD4U5LWYjEDB/YZKrIH7tQts8B4IeYxzHGZ+QYBAmmHY55RzT/WnrXEeJzw3h6wU37//scGR0SY5Th2F+vQk7kQtTidH1NvBaCTjuqFAGKgLS1WYOQXzPHMW2e1NeBeVMUBx59tOOUjH1cHbX1pOFwWXFLC96UaaLKmW/YOD6gBTS/rtPamUJX68JtcqA5L0BZFSYYIiJ5VcizmhB21gp7xpH4+b9mTZspe0vPDEfIxi/85rvwuklchqZRDcevS5I77AnlErYKS7h/pizHJxLMMqrxtWbxDB3Sct7z2nTdIAFrfuoFIt80OaLHpPy3IkGuWPVYHEmW6WUrHk+lPnvg1bw=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Tides-of-Barnegat_4398
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy